from . import hr_hospital_person
from . import hr_hospital_patient
from . import hr_hospital_sickness
from . import hr_hospital_patient_card
from . import hr_hospital_doctor
from . import hr_hospital_diagnose
from . import hr_hospital_sickness_category
from . import hr_hospital_visit
from . import hr_hospital_history_doctor
from . import hr_hospital_research_type
from . import hr_hospital_research
from . import hr_hospital_sample_type
from . import hr_hospital_sample
